### ISSUE TITLE
Cockpit Admin Panel

### ISSUE THREAD

**Issue by ghost** [viktorstrate/Portfolio-Template#1]
When you go to the admin directory it says

" 404
Uuuups, Page not found. "

**Comment by viktorstrate** [comment]
Works now

**Comment by ghost** [comment]
OK, thanks. Sorry I'm not able to watch the stream or work on the template
with you :( I'm away all of next week so yeah - See you sometime at the end
of next week!

**Comment by viktorstrate** [comment]
From Monday?

**Comment by ghost** [comment]
Yep
